In [1]:
%load_ext autoreload
%autoreload 2

import sys

sys.path.append(f"./../")
from src.graphs import StaticGraph

In [2]:
import numpy as np
from math import factorial

def zassenhaus_exponent(X, Y, epsilon):
    """
    Compute the exponent part of the Zassenhaus formula for t=1.
    
    Parameters:
    X, Y: numpy arrays or matrices
    epsilon: desired error tolerance
    
    Returns:
    List of terms in the Zassenhaus expansion
    """
    terms = [X, Y]  # First term is X, second term is Y
    n = 1
    
    while True:
        # Compute the next term
        new_term = compute_zassenhaus_term(X, Y, n)
        
        # Add the new term to the list
        terms.append(new_term / factorial(n + 1))
        
        # Check if the error is small enough
        if np.linalg.norm(new_term) / factorial(n + 1) < epsilon:
            break
        
        n += 1
    
    return terms

def compute_zassenhaus_term(X, Y, n):
    """
    Compute the n-th term in the Zassenhaus expansion.
    """
    if n == 1:
        return 1/2 * (np.dot(X, Y) - np.dot(Y, X))
    else:
        # Recursive computation of higher-order terms
        prev_term = compute_zassenhaus_term(X, Y, n-1)
        return np.dot(X, prev_term) - np.dot(prev_term, X)

In [3]:
import numpy as np

def calculate_adjacency_matrix(edges, vertices):
    """
    Calculate the adjacency matrix for a given list of edges and vertices.
    
    Parameters:
    edges: List of tuples representing edges (vertex pairs)
    vertices: List of vertices in the desired order
    
    Returns:
    numpy array: Adjacency matrix
    """
    # Create a mapping of vertices to their index in the matrix
    vertex_to_index = {v: i for i, v in enumerate(vertices)}
    
    # Create an empty adjacency matrix filled with zeros
    num_vertices = len(vertices)
    adj_matrix = np.zeros((num_vertices, num_vertices), dtype=int)
    
    # Fill the adjacency matrix based on the edges
    for edge in edges:
        v1, v2 = edge
        if v1 in vertex_to_index and v2 in vertex_to_index:
            i, j = vertex_to_index[v1], vertex_to_index[v2]
            adj_matrix[i][j] = 1
            adj_matrix[j][i] = 1  # For undirected graph
    
    return adj_matrix

# Example usage
edges = [(0,1), (0,2)]
vertices = [0, 1, 2, 3, 4, 5, 6, 7]  # Note: including vertex 3 which isn't in any edge

result = calculate_adjacency_matrix(edges, vertices)

print("Vertices:", vertices)
print("Edges:", edges)
print("Adjacency Matrix:")
print(result)

Vertices: [0, 1, 2, 3, 4, 5, 6, 7]
Edges: [(0, 1), (0, 2)]
Adjacency Matrix:
[[0 1 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [8]:
mat1 = calculate_adjacency_matrix([(0,1)], vertices)
mat2 = calculate_adjacency_matrix([(0,2)], vertices)
epsilon = 1e-6

result = zassenhaus_exponent(mat1, mat2, epsilon)

print("Zassenhaus exponent terms:")
for i, term in enumerate(result):
    print(f"Term {i}:")
    print(term)
    print()

Zassenhaus exponent terms:
Term 0:
[[0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

Term 1:
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

Term 2:
[[ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.25  0.    0.    0.    0.    0.  ]
 [ 0.   -0.25  0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]]

Term 3:
[[0.         0.         0.08333333 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.08333333 0.         0.         0.         0.     